version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: trip_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trip-network
    profiles:
      - dev
      - pre_deployment
volumes:
  postgres_data:

networks:
  trip-network: