version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: trip_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trip-network
    profiles:
      - dev

  bonvoyal-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - TRIP_FORM_SUBMISSION_SNS_ARN=${TRIP_FORM_SUBMISSION_SNS_ARN}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      -
    volumes:
      - ~/.aws:/root/.aws:ro
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - trip-network

volumes:
  postgres_data:

networks:
  trip-network:
